#!/usr/bin/env python3
"""threat-intel — AI 驱动的威胁情报分析面板

基于 Gemma-4-E4B-it + LoRA (Cybersecurity-Dataset) 微调模型。

功能:
  - IOC 分析 (IP/域名/哈希/URL)
  - CVE 漏洞解读
  - APT 报告分析
  - 自由情报分析
  - 结构化输出: TTPs 映射 | 风险评级 | IOC 提取 | 处置建议
  - 历史记录 + Markdown 报告导出

用法:
  python3 threat-intel.py                          # 交互面板
  python3 threat-intel.py --ioc "185.220.101.34"   # 快速 IOC 分析
  python3 threat-intel.py --cve "CVE-2024-3094"    # CVE 分析
  python3 threat-intel.py -f report.txt -o out.md  # 文件分析并导出
"""

import json
import re
import argparse
import hashlib
from datetime import datetime
from dataclasses import dataclass, field
from typing import Optional
from enum import Enum

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel


# ══════════════════════════════════════════════════════
# 数据模型
# ══════════════════════════════════════════════════════

class RiskLevel(Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class IntelType(Enum):
    IOC = "ioc"
    CVE = "cve"
    APT_REPORT = "apt_report"
    MALWARE = "malware"
    RAW = "raw"


@dataclass
class IOC:
    """Indicator of Compromise"""
    type: str          # ip, domain, url, hash_md5, hash_sha256, email
    value: str
    confidence: str = "medium"


@dataclass
class TTPMapping:
    """MITRE ATT&CK Technique Mapping"""
    tactic: str
    technique_id: str
    technique_name: str
    description: str


@dataclass
class IntelReport:
    """结构化威胁情报报告"""
    report_id: str
    timestamp: str
    intel_type: IntelType
    summary: str
    risk_level: RiskLevel
    ttps: list = field(default_factory=list)
    iocs: list = field(default_factory=list)
    affected_systems: list = field(default_factory=list)
    recommendations: list = field(default_factory=list)
    related_threats: list = field(default_factory=list)
    raw_analysis: str = ""

    def to_markdown(self) -> str:
        """生成 Markdown 格式报告"""
        md = f"""# Threat Intelligence Report

**ID**: `{self.report_id}`
**Generated**: {self.timestamp}
**Type**: {self.intel_type.value}
**Risk Level**: {'🔴' if self.risk_level.value in ('critical','high') else '🟡' if self.risk_level.value == 'medium' else '🟢'} **{self.risk_level.value.upper()}**

---

## Summary

{self.summary}

---

## MITRE ATT&CK Mapping
"""
        if self.ttps:
            md += "\n| Tactic | Technique | ID | Description |\n"
            md += "|--------|-----------|----|-------------|\n"
            for t in self.ttps:
                md += f"| {t.tactic} | {t.technique_name} | `{t.technique_id}` | {t.description} |\n"
        else:
            md += "\n*No TTPs identified.*\n"

        if self.iocs:
            md += "\n## Extracted IOCs\n\n"
            md += "| Type | Value | Confidence |\n"
            md += "|------|-------|------------|\n"
            for ioc in self.iocs:
                md += f"| `{ioc.type}` | `{ioc.value}` | {ioc.confidence} |\n"

        if self.affected_systems:
            md += "\n## Affected Systems\n\n"
            for s in self.affected_systems:
                md += f"- {s}\n"

        if self.recommendations:
            md += "\n## Recommendations\n\n"
            for i, r in enumerate(self.recommendations, 1):
                md += f"{i}. {r}\n"

        if self.related_threats:
            md += "\n## Related Threats\n\n"
            for t in self.related_threats:
                md += f"- {t}\n"

        md += f"\n---\n*Generated by AI Threat Intelligence Engine | {datetime.now().strftime('%Y-%m-%d %H:%M')} UTC*"
        return md

    def to_summary(self) -> str:
        """终端友好摘要"""
        lines = [
            f"{'='*60}",
            f"  {self.risk_level.value.upper()} | Type: {self.intel_type.value} | ID: {self.report_id}",
            f"{'='*60}",
            f"  {self.summary[:200]}",
            f"",
            f"  TTPs Mapped: {len(self.ttps)}",
            f"  IOCs Extracted: {len(self.iocs)}",
            f"  Recommendations: {len(self.recommendations)}",
        ]
        if self.ttps:
            lines.append(f"\n  MITRE ATT&CK:")
            for t in self.ttps[:5]:
                lines.append(f"    [{t.technique_id}] {t.technique_name} → {t.tactic}")
        if self.iocs:
            lines.append(f"\n  IOCs:")
            for ioc in self.iocs[:8]:
                lines.append(f"    {ioc.type}: {ioc.value} ({ioc.confidence})")
        if self.recommendations:
            lines.append(f"\n  Top Recommendations:")
            for r in self.recommendations[:3]:
                lines.append(f"    • {r}")
        lines.append(f"{'='*60}")
        return "\n".join(lines)


# ══════════════════════════════════════════════════════
# System Prompt — 关键：JSON 结构化输出
# ══════════════════════════════════════════════════════

SYSTEM_PROMPT = """You are a senior threat intelligence analyst. Analyze the provided intelligence and output a structured JSON report.

Follow this EXACT JSON schema:

```json
{
  "summary": "one paragraph summarizing the threat, its impact, and context",
  "risk_level": "critical|high|medium|low|info",
  "ttps": [
    {
      "tactic": "MITRE ATT&CK tactic name",
      "technique_id": "TXXXX",
      "technique_name": "technique name",
      "description": "how this technique applies to this threat"
    }
  ],
  "iocs": [
    {
      "type": "ip|domain|url|hash_md5|hash_sha256|email",
      "value": "the actual IOC value",
      "confidence": "high|medium|low"
    }
  ],
  "affected_systems": ["affected software, OS, or platform names"],
  "recommendations": ["specific, actionable defensive recommendations"],
  "related_threats": ["related threat actor groups, campaigns, or malware families"]
}
```

Rules:
- Map ALL findings to MITRE ATT&CK framework (use real technique IDs).
- Extract ALL observable IOCs from the input.
- Provide CONCRETE, actionable recommendations (not generic advice).
- If the input is benign or not threat-related, set risk_level to "info" and explain why.
- Output ONLY the JSON object, no other text before or after."""


# ══════════════════════════════════════════════════════
# 核心推理引擎
# ══════════════════════════════════════════════════════

class ThreatIntelEngine:
    """威胁情报推理引擎 — 封装模型加载和推理"""

    def __init__(self, base_model_dir: str, lora_dir: str):
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        print(f"[*] Loading model on {self.device}...")

        base = AutoModelForCausalLM.from_pretrained(
            base_model_dir,
            torch_dtype=torch.bfloat16,
            low_cpu_mem_usage=True,
            trust_remote_code=True,
        ).to(self.device)

        self.model = PeftModel.from_pretrained(base, lora_dir)
        self.model.eval()
        self.tokenizer = AutoTokenizer.from_pretrained(lora_dir, trust_remote_code=True)
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token
        print("[*] Model loaded successfully.")

    def _generate(self, instruction: str, user_input: str) -> str:
        """底层生成接口"""
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"{instruction}\n\n{user_input}"},
        ]

        inputs = self.tokenizer.apply_chat_template(
            messages, tokenize=True, add_generation_prompt=True,
            return_dict=True, return_tensors="pt",
        )
        inputs = {k: v.to(self.device) for k, v in inputs.items()}

        input_len = inputs["input_ids"].shape[-1]

        with torch.no_grad():
            outputs = self.model.generate(
                **inputs,
                max_new_tokens=512,
                do_sample=False,
                pad_token_id=self.tokenizer.pad_token_id,
                eos_token_id=self.tokenizer.eos_token_id,
            )

        return self.tokenizer.decode(
            outputs[0][input_len:], skip_special_tokens=True
        ).strip()

    def _parse_json(self, raw: str) -> dict:
        """容错 JSON 解析"""
        # 尝试直接解析
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            pass

        # 尝试提取 {...} 块
        match = re.search(r'\{[\s\S]*\}', raw)
        if match:
            try:
                return json.loads(match.group())
            except json.JSONDecodeError:
                pass

        # 兜底：纯文本
        return {
            "summary": raw[:500],
            "risk_level": "medium",
            "ttps": [],
            "iocs": [],
            "affected_systems": [],
            "recommendations": [],
            "related_threats": [],
        }

    # ─── 四个分析接口 ──────────────────────────────

    def analyze_ioc(self, ioc_value: str) -> IntelReport:
        """分析单个 IOC"""
        raw = self._generate(
            "Analyze this Indicator of Compromise. What threat does it indicate? "
            "Map to MITRE ATT&CK, assess risk, and recommend defensive actions:",
            ioc_value,
        )
        data = self._parse_json(raw)
        return IntelReport(
            report_id=self._hash_id(ioc_value),
            timestamp=datetime.now().isoformat(),
            intel_type=IntelType.IOC,
            raw_analysis=raw,
            summary=data.get("summary", ""),
            risk_level=RiskLevel(data.get("risk_level", "medium")),
            ttps=[TTPMapping(**t) for t in data.get("ttps", [])],
            iocs=[IOC(**i) for i in data.get("iocs", [])],
            affected_systems=data.get("affected_systems", []),
            recommendations=data.get("recommendations", []),
            related_threats=data.get("related_threats", []),
        )

    def analyze_cve(self, cve_id: str, description: str = "") -> IntelReport:
        """分析 CVE 漏洞"""
        user_input = f"CVE: {cve_id}"
        if description:
            user_input += f"\n\nDescription: {description}"

        raw = self._generate(
            "Analyze this CVE vulnerability. Assess real-world impact, "
            "exploitability, affected systems, known threat actors exploiting it, "
            "and provide concrete mitigation steps:",
            user_input,
        )
        data = self._parse_json(raw)
        return IntelReport(
            report_id=self._hash_id(cve_id),
            timestamp=datetime.now().isoformat(),
            intel_type=IntelType.CVE,
            raw_analysis=raw,
            summary=data.get("summary", ""),
            risk_level=RiskLevel(data.get("risk_level", "medium")),
            ttps=[TTPMapping(**t) for t in data.get("ttps", [])],
            iocs=[IOC(**i) for i in data.get("iocs", [])],
            affected_systems=data.get("affected_systems", []),
            recommendations=data.get("recommendations", []),
            related_threats=data.get("related_threats", []),
        )

    def analyze_apt_report(self, report_text: str) -> IntelReport:
        """分析 APT 威胁报告"""
        raw = self._generate(
            "Analyze this threat intelligence report. Extract TTPs used by the "
            "threat actor, identify all IOCs, map to MITRE ATT&CK framework, "
            "and provide defensive recommendations:",
            report_text[:3000],
        )
        data = self._parse_json(raw)
        return IntelReport(
            report_id=self._hash_id(report_text[:100]),
            timestamp=datetime.now().isoformat(),
            intel_type=IntelType.APT_REPORT,
            raw_analysis=raw,
            summary=data.get("summary", ""),
            risk_level=RiskLevel(data.get("risk_level", "medium")),
            ttps=[TTPMapping(**t) for t in data.get("ttps", [])],
            iocs=[IOC(**i) for i in data.get("iocs", [])],
            affected_systems=data.get("affected_systems", []),
            recommendations=data.get("recommendations", []),
            related_threats=data.get("related_threats", []),
        )

    def analyze_raw(self, text: str) -> IntelReport:
        """通用威胁情报分析"""
        raw = self._generate(
            "Analyze the following threat intelligence. Identify the threat type, "
            "extract all IOCs, map relevant techniques to MITRE ATT&CK, "
            "assess overall risk, and recommend defensive actions:",
            text[:3000],
        )
        data = self._parse_json(raw)
        return IntelReport(
            report_id=self._hash_id(text[:100]),
            timestamp=datetime.now().isoformat(),
            intel_type=IntelType.RAW,
            raw_analysis=raw,
            summary=data.get("summary", ""),
            risk_level=RiskLevel(data.get("risk_level", "medium")),
            ttps=[TTPMapping(**t) for t in data.get("ttps", [])],
            iocs=[IOC(**i) for i in data.get("iocs", [])],
            affected_systems=data.get("affected_systems", []),
            recommendations=data.get("recommendations", []),
            related_threats=data.get("related_threats", []),
        )

    def _hash_id(self, seed: str) -> str:
        return hashlib.md5(seed.encode()).hexdigest()[:12]


# ══════════════════════════════════════════════════════
# 交互面板
# ══════════════════════════════════════════════════════

class ThreatIntelPanel:
    """命令行交互式威胁情报面板"""

    BANNER = """
╔══════════════════════════════════════════════╗
║         🔴 AI 威胁情报分析面板 v1.0          ║
║    Gemma-4-E4B-it + Cybersecurity LoRA       ║
╠══════════════════════════════════════════════╣
║  [1] IOC 分析  — IP / 域名 / 哈希 / URL     ║
║  [2] CVE 解读  — 漏洞深度分析                ║
║  [3] APT 报告  — 威胁报告结构化提取           ║
║  [4] 自由分析  — 任意情报文本                ║
║  [5] 历史记录  — 查看已分析报告               ║
║  [6] 导出报告  — Markdown 格式               ║
║  [q] 退出                                   ║
╚══════════════════════════════════════════════╝
"""

    def __init__(self, engine: ThreatIntelEngine):
        self.engine = engine
        self.history: list[IntelReport] = []

    def run(self):
        print(self.BANNER)

        while True:
            try:
                choice = input("\n[panel] ▶ ").strip().lower()
            except (EOFError, KeyboardInterrupt):
                print("\nExiting.")
                break

            if choice in ("q", "quit", "exit"):
                break
            elif choice == "1":
                self._handle_ioc()
            elif choice == "2":
                self._handle_cve()
            elif choice == "3":
                self._handle_apt()
            elif choice == "4":
                self._handle_raw()
            elif choice == "5":
                self._show_history()
            elif choice == "6":
                self._export_report()
            elif choice:
                print("[!] Invalid choice. Enter 1-6 or q.")

    def _handle_ioc(self):
        val = input("  IOC value (e.g. 185.220.101.34): ").strip()
        if not val:
            return
        print("  [*] Analyzing...")
        report = self.engine.analyze_ioc(val)
        self.history.append(report)
        print(report.to_summary())

    def _handle_cve(self):
        cve = input("  CVE ID (e.g. CVE-2024-3094): ").strip()
        if not cve:
            return
        desc = input("  Description (optional, Enter to skip): ").strip()
        print("  [*] Analyzing...")
        report = self.engine.analyze_cve(cve, desc)
        self.history.append(report)
        print(report.to_summary())

    def _handle_apt(self):
        print("  Paste APT report text (end with an empty line):")
        lines = []
        while True:
            try:
                line = input()
            except EOFError:
                break
            if not line:
                break
            lines.append(line)
        if not lines:
            return
        text = "\n".join(lines)
        print(f"  [*] Analyzing {len(text)} chars...")
        report = self.engine.analyze_apt_report(text)
        self.history.append(report)
        print(report.to_summary())

    def _handle_raw(self):
        print("  Paste intelligence text (end with an empty line):")
        lines = []
        while True:
            try:
                line = input()
            except EOFError:
                break
            if not line:
                break
            lines.append(line)
        if not lines:
            return
        text = "\n".join(lines)
        print(f"  [*] Analyzing {len(text)} chars...")
        report = self.engine.analyze_raw(text)
        self.history.append(report)
        print(report.to_summary())

    def _show_history(self):
        if not self.history:
            print("  No reports yet.")
            return
        for i, r in enumerate(self.history):
            icon = "🔴" if r.risk_level.value in ("critical", "high") else "🟡" if r.risk_level.value == "medium" else "🟢"
            print(f"  [{i}] {icon} {r.report_id} | {r.intel_type.value:12s} | {r.summary[:80]}...")

    def _export_report(self):
        if not self.history:
            print("  No reports to export.")
            return
        self._show_history()
        try:
            idx = int(input("  Export which index? "))
        except ValueError:
            return
        if 0 <= idx < len(self.history):
            fname = f"threat_intel_report_{datetime.now():%Y%m%d_%H%M%S}.md"
            with open(fname, "w", encoding="utf-8") as f:
                f.write(self.history[idx].to_markdown())
            print(f"  [+] Exported to {fname}")
        else:
            print("  [!] Invalid index.")


# ══════════════════════════════════════════════════════
# 入口
# ══════════════════════════════════════════════════════

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="AI 威胁情报分析面板 — Gemma-4-E4B-it + Cybersecurity LoRA",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 threat-intel.py                              # 交互面板
  python3 threat-intel.py --ioc "185.220.101.34"       # 快速 IOC 分析
  python3 threat-intel.py --cve "CVE-2024-3094"        # CVE 分析
  python3 threat-intel.py -f apt29.txt -o report.md    # 文件分析 + 导出
        """,
    )
    parser.add_argument("--model", default="./models/google/gemma-4-E4B-it",
                        help="Base model directory")
    parser.add_argument("--lora", default="./gemma4-it-cybersec-lora-ms-single-gpu",
                        help="LoRA adapter directory")
    parser.add_argument("--ioc", help="Quick IOC analysis")
    parser.add_argument("--cve", help="Quick CVE analysis")
    parser.add_argument("--file", "-f", help="Read intelligence from file")
    parser.add_argument("--output", "-o", help="Output Markdown report path")
    args = parser.parse_args()

    engine = ThreatIntelEngine(args.model, args.lora)

    if args.ioc:
        report = engine.analyze_ioc(args.ioc)
        print(report.to_summary())
        if args.output:
            with open(args.output, "w", encoding="utf-8") as f:
                f.write(report.to_markdown())
    elif args.cve:
        report = engine.analyze_cve(args.cve)
        print(report.to_summary())
        if args.output:
            with open(args.output, "w", encoding="utf-8") as f:
                f.write(report.to_markdown())
    elif args.file:
        with open(args.file, "r", encoding="utf-8") as f:
            text = f.read()
        report = engine.analyze_raw(text)
        print(report.to_summary())
        out_path = args.output or f"threat_intel_report_{datetime.now():%Y%m%d_%H%M%S}.md"
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(report.to_markdown())
        print(f"[+] Report saved to {out_path}")
    else:
        panel = ThreatIntelPanel(engine)
        panel.run()
